version: '3.7'
services:
  jackpot-web:
    image: angular_v16
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env    
    environment:
      - NODE_ENV:dev
      - PORT:4200
    ports:
      - 8080:4200
    volumes:
      - ./:/home/app
      - /home/app/node_modules

  api:
    container_name: jack-pot-api
    image: nestjs
    environment:
      - NODE_ENV:${NODE_ENV}
      - PORT:${BACKEND_PORT}
    build:
      context: ../jackpot-api
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: ["npm", "run", "start:${NODE_ENV}"]
    ports:
      - 3000:3000

    volumes:
      - ../jackpot-api/:/home/app
      - /home/app/node_modules